### ISSUE TITLE
Error on email 

### ISSUE THREAD

**Issue by vtemian** [zalmanu/project-spartan#213]
```[2016-07-27 18:30:24,712: INFO/MainProcess] Received task: posts.tasks.notify_spartans[5486a942-c7a0-4c12-8ce7-288f06e3e52c]
[2016-07-27 18:30:25,068: ERROR/MainProcess] Task posts.tasks.email_user[27173156-bebe-414d-af4d-a62bb59a98f3] raised unexpected: SMTPAuthenticationError(535, '5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/answer/14257 x6sm7618851wjk.26 - gsmtp')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/project-spartan/spartan/posts/tasks.py", line 67, in email_user
    mail.send()
  File "/usr/local/lib/python2.7/site-packages/django/core/mail/message.py", line 292, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/usr/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 100, in send_messages
    new_conn_created = self.open()
  File "/usr/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 67, in open
    self.connection.login(self.username, self.password)
  File "/usr/local/lib/python2.7/smtplib.py", line 622, in login
    raise SMTPAuthenticationError(code, resp)
SMTPAuthenticationError: (535, '5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/answer/14257 x6sm7618851wjk.26 - gsmtp')
```
SMTP username and password not configured

**Comment by emanuelcovaci** [comment]
Da ,am schimbat parola de la email si de asta nu merge pe server nu e parola noua de la email inca
